export const QUERIES_LABELS = {
  PAGE_TITLE: 'Consultas',
  CONNECTION_SELECT_LABEL: 'Conexión',
  CONNECTION_SELECT_PLACEHOLDER: 'Selecciona una conexión...',
  SQL_LABEL: 'Consulta SQL',
  SQL_PLACEHOLDER: 'Escribe tu consulta SELECT aquí...',
  EXECUTE_BUTTON: 'Ejecutar',
  EXECUTING: 'Ejecutando...',
  SAVE_BUTTON: 'Guardar consulta',
  SAVED_QUERIES_TITLE: 'Consultas guardadas',
  NO_SAVED_QUERIES: 'No tienes consultas guardadas.',
  QUERY_NAME_LABEL: 'Nombre',
  QUERY_NAME_PLACEHOLDER: 'Nombre de la consulta',
  DESCRIPTION_LABEL: 'Descripción',
  DESCRIPTION_PLACEHOLDER: 'Descripción opcional',
  SAVE_MODAL_TITLE: 'Guardar consulta',
  SAVE_MODAL_BUTTON: 'Guardar',
  CANCEL_BUTTON: 'Cancelar',
  DELETE_BUTTON: 'Eliminar',
  LOAD_BUTTON: 'Cargar',
  EDIT_BUTTON: 'Editar',
  CONFIRM_DELETE: '¿Eliminar esta consulta guardada?',
  RESULTS_TITLE: 'Resultados',
  ROW_COUNT: 'filas',
  NO_RESULTS: 'La consulta no retornó resultados.',
  NO_CONNECTION_SELECTED: 'Selecciona una conexión para ejecutar consultas.',
  REQUIRED_FIELDS: 'Todos los campos son obligatorios.',
  EXPAND_GROUP: 'Expandir grupo',
  COLLAPSE_GROUP: 'Colapsar grupo',
  EXPAND_QUERY: 'Ver detalles',
  COLLAPSE_QUERY: 'Ocultar detalles',
  UNKNOWN_CONNECTION: 'Conexión desconocida',
} as const;
