export const CHARTS_LABELS = {
  PAGE_TITLE: 'Gráficas',
  CREATE_BUTTON: 'Nueva gráfica',
  EDIT_BUTTON: 'Editar',
  DELETE_BUTTON: 'Eliminar',
  CONFIRM_DELETE: '¿Eliminar esta gráfica?',
  NO_CHARTS: 'No tienes gráficas creadas.',
  CHART_NAME_LABEL: 'Nombre',
  CHART_NAME_PLACEHOLDER: 'Nombre de la gráfica',
  CONNECTION_LABEL: 'Conexión',
  CONNECTION_PLACEHOLDER: 'Selecciona una conexión...',
  SAVED_QUERY_LABEL: 'Consulta guardada (opcional)',
  SAVED_QUERY_PLACEHOLDER: 'Selecciona una consulta...',
  SQL_LABEL: 'Consulta SQL',
  SQL_PLACEHOLDER: 'Escribe tu consulta SELECT aquí...',
  CHART_TYPE_LABEL: 'Tipo de gráfica',
  X_COLUMN_LABEL: 'Columna X',
  X_COLUMN_PLACEHOLDER: 'Selecciona la columna X...',
  Y_COLUMNS_LABEL: 'Columna(s) Y',
  Y_COLUMNS_PLACEHOLDER: 'Selecciona columna(s) Y...',
  TITLE_LABEL: 'Título de la gráfica',
  TITLE_PLACEHOLDER: 'Título opcional',
  PREVIEW_BUTTON: 'Vista previa',
  PREVIEWING: 'Generando...',
  SAVE_BUTTON: 'Guardar',
  SAVING: 'Guardando...',
  CANCEL_BUTTON: 'Cancelar',
  BACK_BUTTON: 'Volver',
  NO_DATA: 'No hay datos para mostrar.',
  CHART_TYPE_OPTIONS: {
    bar: 'Barras',
    line: 'Líneas',
    pie: 'Pastel',
    scatter: 'Dispersión',
    histogram: 'Histograma',
  },
} as const;
