export const CONNECTIONS_LABELS = {
  PAGE_TITLE: 'Conexiones',
  ADD_BUTTON: 'Nueva conexión',
  NAME_LABEL: 'Nombre',
  HOST_LABEL: 'Servidor',
  PORT_LABEL: 'Puerto',
  DATABASE_LABEL: 'Base de datos',
  USERNAME_LABEL: 'Usuario',
  PASSWORD_LABEL: 'Contraseña',
  SAVE_BUTTON: 'Guardar',
  CANCEL_BUTTON: 'Cancelar',
  DELETE_BUTTON: 'Eliminar',
  TEST_BUTTON: 'Probar conexión',
  TESTING: 'Probando...',
  TEST_SUCCESS: 'Conexión exitosa',
  TEST_FAILED: 'Error de conexión',
  CONFIRM_DELETE: '¿Eliminar esta conexión?',
  NO_CONNECTIONS: 'No tienes conexiones registradas.',
  SCHEMAS_TITLE: 'Esquemas',
  TABLES_TITLE: 'Tablas',
  COLUMNS_TITLE: 'Columnas',
  COLUMN_NAME: 'Columna',
  DATA_TYPE: 'Tipo',
  NULLABLE: 'Nulo',
  EXPLORE_BUTTON: 'Explorar',
  BACK_BUTTON: 'Volver',
  REQUIRED_FIELDS: 'Todos los campos son obligatorios.',
} as const;
